# Generated by Django 6.1 on 2026-08-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('education', 'Education & Institutional'), ('health', 'Health & Foodservice'), ('housing', 'Community & Housing'), ('institutional', 'Institutional & Hospitality'), ('residential', 'Residential Design'), ('concept', 'Concept Studies')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
