# Generated by Django 6.1 on 2026-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education & Institutional'), ('health', 'Health & Foodservice'), ('housing', 'Community & Housing'), ('institutional', 'Institutional & Hospitality'), ('residential', 'Residential Design'), ('concept', 'Concept Studies')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
    ]
