# Generated by Django 6.1 on 2026-09-07 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_newslettersubscriber_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('before', 'Before'), ('after', 'After')], default='gallery', max_length=10),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='pair_key',
            field=models.CharField(blank=True, help_text="Set the same value on a 'before' and 'after' image of the same view (e.g. 'view-1') so the frontend can pair them into a toggle.", max_length=50),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.CharField(choices=[('education', 'Education & Institutional'), ('health', 'Health & Foodservice'), ('housing', 'Community & Housing'), ('institutional', 'Institutional & Hospitality'), ('residential', 'Residential Design'), ('concept', 'Concept Studies'), ('interior', 'Interior Design')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('education', 'Education & Institutional'), ('health', 'Health & Foodservice'), ('housing', 'Community & Housing'), ('institutional', 'Institutional & Hospitality'), ('residential', 'Residential Design'), ('concept', 'Concept Studies'), ('interior', 'Interior Design')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='core.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
