# Generated by Django 6.1 on 2026-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projectimage_image_type_projectimage_pair_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='section',
            field=models.CharField(blank=True, help_text="Optional named gallery, e.g. 'The Finished Space', 'Reception', 'Co-Working & Director's Office', 'As Built'. Leave blank for the general intro gallery at the top of the page. Images sharing the same section render together as one grouped gallery, in 'order'.", max_length=100),
        ),
    ]
